### ISSUE TITLE
Admin not being able to use moderator level commands.

### ISSUE THREAD

**Issue by defualo1** [va1kio/commander#35] opened 2021-03-16 21:54 UTC
As an admin I'm not able to use a command that a moderator can do, that I should be able to do because I can see it. 
All that showed up in the console was the message that shows when a command doesn't work.

**Comment by JEK0x81D** [comment] 2021-03-16 21:59
Could you please provide your settings script as well as the command in question that is not working and the message that shows in the output log?

**Comment by defualo1** [comment] 2021-03-16 22:06
![image](https://user-images.githubusercontent.com/80792446/111386192-449de100-8682-11eb-9ba4-5c681de503a4.png)
![image](https://user-images.githubusercontent.com/80792446/111386088-1cae7d80-8682-11eb-8cf7-09b4fa692152.png)
![image](https://user-images.githubusercontent.com/80792446/111386210-4ebfdf80-8682-11eb-8346-81236b8d283b.png)

**Comment by JEK0x81D** [comment] 2021-03-16 22:18
The image is cut in to pieces which makes it hard to discern what is where, please copy and paste the full settings script into a code block here or a pastebin so that I can further investigate. I will say also that moderators should go along with the administrators in the Admins table. The name is slightly misleading as it was made before permission groups were a thing.

**Comment by JEK0x81D** [comment] 2021-03-16 23:09
This is due to an issue caused by the name of the ModuleScript and the display name of the package. Your configuration should be right however because of how packages are handled it has some issues, this will be fixed in a future update.

**Closed** 2021-03-21 14:14 UTC
Labels: bug
